window.sotoThoughts = [
  {"Line": "Arise, awake, and stop not till the goal is reached.", "Said_by": "Swami Vivekananda"},
  {"Line": "You have to grow from the inside out. There is no other teacher but your own soul.", "Said_by": "Swami Vivekananda"},
  {"Line": "Truth can be stated in a thousand different ways, yet each one can be true.", "Said_by": "Swami Vivekananda"},
  {"Line": "The greatest religion is to be true to your own nature. Have faith in yourselves.", "Said_by": "Swami Vivekananda"},
  {"Line": "Strength is Life, Weakness is Death. Expansion is Life, Contraction is Death.", "Said_by": "Swami Vivekananda"},
  {"Line": "All differences in this world are of degree, and not of kind, because oneness is the secret of everything.", "Said_by": "Swami Vivekananda"},
  {"Line": "Take up one idea. Make that one idea your life; dream of it; think of it; live on that idea.", "Said_by": "Swami Vivekananda"},
  {"Line": "The fire that warms us can also consume us; it is not the fault of the fire.", "Said_by": "Swami Vivekananda"},
  {"Line": "Whatever you think, that you will be. If you think yourselves weak, weak you will be.", "Said_by": "Swami Vivekananda"},
  {"Line": "In a day, when you don't come across any problems, you can be sure that you are travelling in a wrong path.", "Said_by": "Swami Vivekananda"},
  {"Line": "All the powers in the universe are already ours. It is we who have put our hands before our eyes.", "Said_by": "Swami Vivekananda"},
  {"Line": "Talk to yourself once in a day, otherwise you may miss meeting an intelligent person in this world.", "Said_by": "Swami Vivekananda"},
  {"Line": "The world is the great gymnasium where we come to make ourselves strong.", "Said_by": "Swami Vivekananda"},
  {"Line": "The great secret of true success, of quite happiness, is this: the man or woman who asks for no return.", "Said_by": "Swami Vivekananda"},
  {"Line": "Be not afraid of anything. You will do marvelous work. It is fearlessness that brings Heaven.", "Said_by": "Swami Vivekananda"},
  {"Line": "Stand up, be bold, be strong. Take the whole responsibility on your own shoulders.", "Said_by": "Swami Vivekananda"},
  {"Line": "The brain and muscles must go together. Work, work, work, even unto death.", "Said_by": "Swami Vivekananda"},
  {"Line": "We are what our thoughts have made us; so take care about what you think.", "Said_by": "Swami Vivekananda"},
  {"Line": "Condemn none: if you can stretch out a helping hand, do so. If not, fold your hands.", "Said_by": "Swami Vivekananda"},
  {"Line": "Ask nothing; want nothing in return. Give what you have to give; it will come back to you.", "Said_by": "Swami Vivekananda"},
  {"Line": "You cannot believe in God until you believe in yourself.", "Said_by": "Swami Vivekananda"},
  {"Line": "Neither seek nor avoid, take what comes.", "Said_by": "Swami Vivekananda"},
  {"Line": "Comfort is no test of truth. Truth is often far from being comfortable.", "Said_by": "Swami Vivekananda"},
  {"Line": "The chemical process of the mind is such that it becomes what it contemplates.", "Said_by": "Swami Vivekananda"},
  {"Line": "The concentration of the mind is the source of all knowledge.", "Said_by": "Swami Vivekananda"},
  {"Line": "Seek the science of the soul. The soul is the only reality.", "Said_by": "Swami Vivekananda"},
  {"Line": "The mind is everything. What you think you become.", "Said_by": "Swami Vivekananda"},
  {"Line": "Be searchers of truth, and be brave to stand by the truth.", "Said_by": "Swami Vivekananda"},
  {"Line": "Perfect sincerity, holiness, gigantic willpower, and purity are all-conquering.", "Said_by": "Swami Vivekananda"},
  {"Line": "Do one thing at a time, and while doing it put your whole soul into it.", "Said_by": "Swami Vivekananda"},
  {"Line": "The power of concentration is the only key to the treasure-house of knowledge.", "Said_by": "Swami Vivekananda"},
  {"Line": "Purity, patience, and perseverance are the three essentials to success.", "Said_by": "Swami Vivekananda"},
  {"Line": "Be the witness; look on at the picture of the universe; do not identify with it.", "Said_by": "Swami Vivekananda"},
  {"Line": "The dynamic power of meditation is the highest state that a human being can reach.", "Said_by": "Swami Vivekananda"},
  {"Line": "Have faith in yourself, and stand on that faith.", "Said_by": "Swami Vivekananda"},
  {"Line": "Where can we go to find God if we cannot see Him in our own hearts and in every living being?", "Said_by": "Swami Vivekananda"},
  {"Line": "He who struggles is better than he who never attempts.", "Said_by": "Swami Vivekananda"},
  {"Line": "Every evolution is preceded by an involution.", "Said_by": "Swami Vivekananda"},
  {"Line": "The goal of mankind is knowledge. That knowledge is inherent in man.", "Said_by": "Swami Vivekananda"},
  {"Line": "Self-realization is the true definition of spiritual growth.", "Said_by": "Swami Vivekananda"},
  {"Line": "All knowledge that the world has received comes from the mind.", "Said_by": "Swami Vivekananda"},
  {"Line": "External nature is only internal nature writ large.", "Said_by": "Swami Vivekananda"},
  {"Line": "All energy is only manifestations of the power of the soul.", "Said_by": "Swami Vivekananda"},
  {"Line": "Do not look back, look forward.", "Said_by": "Swami Vivekananda"},
  {"Line": "Unselfishness is more paying, only people have not the patience to practice it.", "Said_by": "Swami Vivekananda"},
  {"Line": "The absolute truth is eternal and cannot be changed by opinion.", "Said_by": "Swami Vivekananda"},
  {"Line": "Infinite patience, infinite purity, and infinite perseverance are required.", "Said_by": "Swami Vivekananda"},
  {"Line": "Each soul is potentially divine.", "Said_by": "Swami Vivekananda"},
  {"Line": "The only religion is to realize the Divine within.", "Said_by": "Swami Vivekananda"},
  {"Line": "Be true to your own vision, and let the world follow.", "Said_by": "Swami Vivekananda"},
  {"Line": "Blessed are those who struggle to manifest the divinity within.", "Said_by": "Swami Vivekananda"},
  {"Line": "All limitations are self-created. Break the bonds of ignorance.", "Said_by": "Swami Vivekananda"},
  {"Line": "Meditation is the key that opens all doors of wisdom.", "Said_by": "Swami Vivekananda"},
  {"Line": "Calmness of mind is the source of tremendous mental power.", "Said_by": "Swami Vivekananda"},
  {"Line": "Realize that you are the master of your own destiny.", "Said_by": "Swami Vivekananda"},
  {"Line": "Manifest the divinity within you, and everything will be harmonious.", "Said_by": "Swami Vivekananda"},
  {"Line": "The highest form of worship is the worship of the Divine in human form.", "Said_by": "Swami Vivekananda"},
  {"Line": "Fill the brain with high thoughts, highest ideals, place them day and night before you.", "Said_by": "Swami Vivekananda"},
  {"Line": "A single thought can transform a human life from within.", "Said_by": "Swami Vivekananda"},
  {"Line": "Purity of mind is the first step towards spiritual awakening.", "Said_by": "Swami Vivekananda"},
  {"Line": "Unshakable devotion to truth is the path of the wise.", "Said_by": "Swami Vivekananda"},
  {"Line": "The light is within you; let it shine forth.", "Said_by": "Swami Vivekananda"},
  {"Line": "Fear is the greatest enemy of human progress.", "Said_by": "Swami Vivekananda"},
  {"Line": "Every work has to pass through these stages - ridicule, opposition, and then acceptance.", "Said_by": "Swami Vivekananda"},
  {"Line": "He who sees the One in the many is the true seer.", "Said_by": "Swami Vivekananda"},
  {"Line": "Purity and unselfishness are the only guardians of the soul.", "Said_by": "Swami Vivekananda"},
  {"Line": "Freedom is the song of the soul; do not bind it with desires.", "Said_by": "Swami Vivekananda"},
  {"Line": "Realize oneness with the universe, and all fear vanishes.", "Said_by": "Swami Vivekananda"},
  {"Line": "The spiritual path is like a sharp razor's edge, yet one must walk it.", "Said_by": "Swami Vivekananda"},
  {"Line": "Wisdom is the destination, and faith is the vehicle.", "Said_by": "Swami Vivekananda"},
  {"Line": "Keep your mind centered on the absolute, and remain peaceful.", "Said_by": "Swami Vivekananda"},
  {"Line": "In true meditation, the self dissolves into infinite consciousness.", "Said_by": "Swami Vivekananda"},
  {"Line": "Let your life be a manifestation of unselfish love.", "Said_by": "Swami Vivekananda"},
  {"Line": "Be steadfast in truth, and your words will carry power.", "Said_by": "Swami Vivekananda"},
  {"Line": "The soul knows no death, no birth, and no decay.", "Said_by": "Swami Vivekananda"},
  {"Line": "Awaken the latent energy within you through yoga.", "Said_by": "Swami Vivekananda"},
  {"Line": "The universe is a projection of the mind; control the mind.", "Said_by": "Swami Vivekananda"},
  {"Line": "Pure love knows no boundaries and seeks no reward.", "Said_by": "Swami Vivekananda"},
  {"Line": "Quiet the waves of the mind to reflect the true self.", "Said_by": "Swami Vivekananda"},
  {"Line": "The highest truth is simple; it is we who complicate it.", "Said_by": "Swami Vivekananda"},
  {"Line": "Service to humanity is service to the Divine.", "Said_by": "Swami Vivekananda"},
  {"Line": "The pure heart is the mirror of the cosmic reality.", "Said_by": "Swami Vivekananda"},
  {"Line": "Let go of all attachments to experience true freedom.", "Said_by": "Swami Vivekananda"},
  {"Line": "The source of infinite joy is within your own heart.", "Said_by": "Swami Vivekananda"},
  {"Line": "Believe in the infinite power of the human spirit.", "Said_by": "Swami Vivekananda"},
  {"Line": "Hold fast to the anchor of truth in the stormy sea of life.", "Said_by": "Swami Vivekananda"},
  {"Line": "True knowledge leads to absolute peace and harmony.", "Said_by": "Swami Vivekananda"},
  {"Line": "Direct your mind's focus inward to find the ultimate source of light.", "Said_by": "Swami Vivekananda"},
  {"Line": "A strong mind can overcome any physical obstacle.", "Said_by": "Swami Vivekananda"},
  {"Line": "Cultivate the habit of seeing divinity in everyone you meet.", "Said_by": "Swami Vivekananda"},
  {"Line": "Patience and perseverance conquer all difficulties.", "Said_by": "Swami Vivekananda"},
  {"Line": "The path of selflessness is the direct route to realization.", "Said_by": "Swami Vivekananda"},
  {"Line": "Stand firm like a rock in the face of life's trials.", "Said_by": "Swami Vivekananda"},
  {"Line": "Infinite strength is the birthright of every human soul.", "Said_by": "Swami Vivekananda"},
  {"Line": "Fill your heart with compassion for all living beings.", "Said_by": "Swami Vivekananda"},
  {"Line": "Calmness is the power that controls all external conditions.", "Said_by": "Swami Vivekananda"},
  {"Line": "Seek the eternal within the transient world.", "Said_by": "Swami Vivekananda"},
  {"Line": "Your own soul is the supreme temple of realization.", "Said_by": "Swami Vivekananda"},
  {"Line": "True spirituality is self-reliance and inner strength.", "Said_by": "Swami Vivekananda"},
  {"Line": "Unbind your mind from the limitations of the past.", "Said_by": "Swami Vivekananda"}
];
